parameters:
- name: AdditionalParameters
  type: object
- name: CloudConfig
  type: object
  default: {}
- name: MatrixConfigs
  type: object
  default: []

jobs:
- ${{ each config in parameters.MatrixConfigs }}:
  - job: generate_matrix_${{ config.Name }}
    variables:
      displayNameFilter: $[ coalesce(variables.jobMatrixFilter, '.*') ]
    pool:
      vmImage: "ubuntu-18.04"
    displayName: Generate ${{ config.Name }} matrix
    steps:
      - pwsh: |
          Write-Host "DISPLAY NAME FILTER: $(displayNameFilter)"
          eng/scripts/job-matrix/Create-JobMatrix.ps1 `
            -ConfigPath ${{ config.Path }} `
            -Selection ${{ config.Selection }} `
            -DisplayNameFilter "$(displayNameFilter)" `
            -Filters @("!container", "SupportedClouds=${{ parameters.CloudConfig.Cloud }}")
        name: generate_job_matrix_${{ config.Name }}
        displayName: Generate Job Matrix

      - pwsh: |
          Write-Host "DISPLAY NAME FILTER: $(displayNameFilter)"
          eng/scripts/job-matrix/Create-JobMatrix.ps1 `
            -ConfigPath ${{ config.Path }} `
            -Selection ${{ config.Selection }} `
            -DisplayNameFilter "$(displayNameFilter)" `
            -Filters @("container=.*", "SupportedClouds=${{ parameters.CloudConfig.Cloud }}")
        name: generate_container_job_matrix_${{ config.Name }}
        displayName: Generate Container Job Matrix

  - template: ./archetype-sdk-tests-jobs.yml
    parameters:
      UsePlatformContainer: false
      Matrix: dependencies.generate_matrix_${{ config.Name }}.outputs['generate_job_matrix_${{ config.Name }}.matrix']
      DependsOn: generate_matrix_${{ config.Name }}
      CloudConfig: ${{ parameters.CloudConfig }}
      ${{ each param in parameters.AdditionalParameters }}:
        ${{ param.key }}: ${{ param.value }}

  - template: ./archetype-sdk-tests-jobs.yml
    parameters:
      UsePlatformContainer: true
      Matrix: dependencies.generate_matrix_${{ config.Name }}.outputs['generate_container_job_matrix_${{ config.Name }}.matrix']
      DependsOn: generate_matrix_${{ config.Name }}
      CloudConfig: ${{ parameters.CloudConfig }}
      ${{ each param in parameters.AdditionalParameters }}:
        ${{ param.key }}: ${{ param.value }}
